<?php

namespace Database\Seeders;

use App\Models\PageSection;
use Illuminate\Database\Seeder;

class PageSectionSeeder extends Seeder
{
    public function run(): void
    {
        $sections = [

            // ─── GLOBAL ───────────────────────────────────────────────────────
            [
                'page'        => 'global',
                'section_key' => 'header',
                'title'       => 'Ujjawal Unnati Foundation',
                'subtitle'    => 'Need Help?',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'global',
                'section_key' => 'footer',
                'title'       => 'Follow Us',
                'subtitle'    => 'Call Us Anytime',
                'body'        => null,
                'button_text' => 'Email Us',
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'global',
                'section_key' => 'footer_quick_links',
                'title'       => 'Quick Links',
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'global',
                'section_key' => 'footer_services',
                'title'       => 'Our Services',
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'global',
                'section_key' => 'footer_support',
                'title'       => 'Support',
                'subtitle'    => 'Help & Support',
                'body'        => null,
                'button_text' => null,
                'button_url'  => '/contact',
                'is_active'   => true,
            ],

            // ─── HOME ─────────────────────────────────────────────────────────
            [
                'page'        => 'home',
                'section_key' => 'hero',
                'title'       => 'Every Life is Important — We Care for You',
                'subtitle'    => 'Welcome to Ujjawal Unnati Foundation',
                'body'        => 'We are Fighting Against Hunger, Child Labour, and Injustice. Join us in empowering communities, protecting rights, and transforming lives across India.',
                'button_text' => 'Donate Now',
                'button_url'  => '/donation',
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'hero_features',
                'title'       => 'Help Families In Need',
                'subtitle'    => 'Your gift can feed a family today',
                'body'        => "Women & Youth Empowerment\nGau Sewa (Cow Protection)\nChild Education & Labour Eradication",
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'about',
                'title'       => 'Empowering Communities, Protecting Rights',
                'subtitle'    => 'About Us',
                'body'        => 'Ujjawal Unnati Foundation is a registered NGO based in Noida, dedicated to creating a society where every woman is empowered, every child is in school, every cow is safe, and every family has food on their plate. We work directly with communities through awareness drives, skill training, legal aid, and ground-level distribution campaigns.',
                'button_text' => 'About Us',
                'button_url'  => '/about',
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'about_feature',
                'title'       => 'Gau Sewa & Community Care',
                'subtitle'    => 'Providing daily care to cows and communities across the region.',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'services',
                'title'       => 'Our Comprehensive Services',
                'subtitle'    => 'What We Do',
                'body'        => 'We fight for women\'s rights, protect cows, eradicate child labour, empower women through skill training, provide quality education, and run hunger-free drives across India.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'causes',
                'title'       => 'Support Our Community Causes',
                'subtitle'    => 'Our Causes',
                'body'        => 'Your donation directly funds Gau Sewa, free education, women empowerment training, and monthly ration drives for families in need.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'programs',
                'title'       => 'Our Empowerment Programs',
                'subtitle'    => 'Our Programs',
                'body'        => 'From the Gau Sewa Gaushala to the Women Entrepreneur Program and Child Education Centres, our programs create sustainable, measurable change in communities.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'counters',
                'title'       => 'Our Impact in Numbers',
                'subtitle'    => 'Impact',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'donate_cta',
                'title'       => 'Your Donation Changes Lives',
                'subtitle'    => 'Donate Now',
                'body'        => 'Every rupee you donate goes directly to the people who need it most — feeding families, educating children, caring for cows, and empowering women across India.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'testimonials',
                'title'       => 'What People Say About Us',
                'subtitle'    => 'Testimonials',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'gallery',
                'title'       => 'Our Image Gallery',
                'subtitle'    => 'Gallery',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'home',
                'section_key' => 'blog',
                'title'       => 'Stories of Impact and Hope',
                'subtitle'    => 'Latest Posts',
                'body'        => 'Explore inspiring stories and updates about our Gau Sewa, women empowerment drives, education camps, and hunger-free initiatives.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── ABOUT ────────────────────────────────────────────────────────
            [
                'page'        => 'about',
                'section_key' => 'hero',
                'title'       => 'About Ujjawal Unnati Foundation',
                'subtitle'    => 'About Us',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'intro',
                'title'       => 'Empowering Communities Since 2015',
                'subtitle'    => 'Who We Are',
                'body'        => '<p>Ujjawal Unnati Foundation is a registered NGO working across Noida, Gautam Budh Nagar, and surrounding districts of Uttar Pradesh. We are dedicated to women empowerment, Gau Sewa (cow protection), child labour eradication, quality education for all, and building a hunger-free India.</p><p>Our work is rooted in direct community engagement — we do not operate from boardrooms, we operate on the ground, alongside the people we serve. Every campaign, training, and distribution drive is carried out by our dedicated volunteers and staff who believe in the dignity and potential of every human being.</p>',
                'button_text' => 'Contact Us',
                'button_url'  => '/contact',
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'approach',
                'title'       => 'Our Approach — Ground-Level, Results-Driven',
                'subtitle'    => 'How We Work',
                'body'        => '<p>We work directly with communities through awareness drives, skill training workshops, legal aid clinics, and regular distribution campaigns. Our approach is built on trust, transparency, and measurable outcomes.</p><p>Every program we run has clear targets, regular monitoring, and community feedback loops to ensure we are truly making a difference — not just on paper, but in real lives.</p>',
                'button_text' => 'Get Involved',
                'button_url'  => '/contact',
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'mission',
                'title'       => 'Our Mission',
                'subtitle'    => null,
                'body'        => 'To empower underprivileged women, protect the rights of cows, eliminate child labour, provide quality education to every child, and ensure no one in our community sleeps hungry.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'vision',
                'title'       => 'Our Vision',
                'subtitle'    => null,
                'body'        => 'A society where every woman is empowered, every child is in school, every cow is safe, and every family has food on their plate — an India that lives up to its values of compassion, respect, and justice.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'values',
                'title'       => 'Our Core Values',
                'subtitle'    => null,
                'body'        => 'Compassion • Integrity • Community • Action • Accountability — these are not just words for us, they are the principles that guide every decision, every program, and every rupee we spend.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'facts',
                'title'       => 'Our Impact in Numbers',
                'subtitle'    => 'Why It Matters',
                'body'        => 'Since 2015, we have served 22,500+ cows, empowered 1,15,000+ women entrepreneurs, transformed 12,000+ lives, and built a community of 2,500+ supporters who believe in our mission.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'about',
                'section_key' => 'cta',
                'title'       => 'Join Our Mission Today',
                'subtitle'    => 'Get Involved',
                'body'        => 'Whether you want to volunteer, donate, or partner with us — every contribution counts. Together, we can build a more compassionate India.',
                'button_text' => 'Contact Us',
                'button_url'  => '/contact',
                'is_active'   => true,
            ],

            // ─── SERVICES ─────────────────────────────────────────────────────
            [
                'page'        => 'services',
                'section_key' => 'hero',
                'title'       => 'Our Services',
                'subtitle'    => 'What We Do',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'services',
                'section_key' => 'intro',
                'title'       => 'Six Ways We Create Change',
                'subtitle'    => 'Our Services',
                'body'        => 'From Gau Sewa to women empowerment, child education to hunger eradication — our six core services address the most pressing needs of our community.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'services',
                'section_key' => 'why_choose',
                'title'       => 'Why Choose Ujjawal Unnati Foundation?',
                'subtitle'    => 'Our Strength',
                'body'        => '<p>We are transparent, accountable, and deeply committed to every cause we take up. 100% of donations go directly to programs. We are registered, audited, and 80G-certified.</p>',
                'button_text' => 'Contact Us',
                'button_url'  => '/contact',
                'is_active'   => true,
            ],

            // ─── PROGRAMS ─────────────────────────────────────────────────────
            [
                'page'        => 'programs',
                'section_key' => 'hero',
                'title'       => 'Our Programs',
                'subtitle'    => 'Empowering Change',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'programs',
                'section_key' => 'intro',
                'title'       => 'Programs That Transform Lives',
                'subtitle'    => 'Our Programs',
                'body'        => 'Our four flagship programs — Gau Sewa, Women Entrepreneur Training, Child Education, and Ration Distribution — are designed to create lasting, measurable change.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── BLOG ─────────────────────────────────────────────────────────
            [
                'page'        => 'blog',
                'section_key' => 'hero',
                'title'       => 'Stories of Impact and Hope',
                'subtitle'    => 'Our Blog',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── TEAM ─────────────────────────────────────────────────────────
            [
                'page'        => 'team',
                'section_key' => 'hero',
                'title'       => 'Our Team',
                'subtitle'    => 'The People Behind Our Mission',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'team',
                'section_key' => 'intro',
                'title'       => 'Driven by Passion, Guided by Purpose',
                'subtitle'    => 'Our Team',
                'body'        => 'Meet the dedicated individuals who work tirelessly every day to empower communities, protect cows, educate children, and feed the hungry across India.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── GALLERY ──────────────────────────────────────────────────────
            [
                'page'        => 'gallery',
                'section_key' => 'hero',
                'title'       => 'Our Gallery',
                'subtitle'    => 'Moments of Impact',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'gallery',
                'section_key' => 'intro',
                'title'       => 'See Our Work in Action',
                'subtitle'    => 'Gallery',
                'body'        => 'From Gau Sewa drives and ration distributions to women training camps and education centres — witness the impact of our work across communities.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── TESTIMONIALS ─────────────────────────────────────────────────
            [
                'page'        => 'testimonials',
                'section_key' => 'hero',
                'title'       => 'Testimonials',
                'subtitle'    => 'What Our Community Says',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'testimonials',
                'section_key' => 'intro',
                'title'       => 'Voices of Trust and Gratitude',
                'subtitle'    => 'Testimonials',
                'body'        => 'Hear from the volunteers, partners, and community members whose lives have been touched by the work of Ujjawal Unnati Foundation.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── DONATION ─────────────────────────────────────────────────────
            [
                'page'        => 'donation',
                'section_key' => 'hero',
                'title'       => 'Make a Donation',
                'subtitle'    => 'Donate Now',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'donation',
                'section_key' => 'intro',
                'title'       => 'Your Generosity Changes Lives',
                'subtitle'    => 'Why Donate?',
                'body'        => 'Every rupee you donate goes directly to the people who need it most. We are 80G-certified — your donation is tax-exempt. 100% transparency, 0% overhead waste.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── CONTACT ──────────────────────────────────────────────────────
            [
                'page'        => 'contact',
                'section_key' => 'hero',
                'title'       => 'Contact Us',
                'subtitle'    => 'Get In Touch',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'contact',
                'section_key' => 'intro',
                'title'       => 'We\'d Love to Hear From You',
                'subtitle'    => 'Contact',
                'body'        => 'Reach out for volunteering opportunities, donation queries, partnership proposals, or any questions about our work. We respond within 24 hours.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],

            // ─── FAQS ─────────────────────────────────────────────────────────
            [
                'page'        => 'faqs',
                'section_key' => 'hero',
                'title'       => 'Frequently Asked Questions',
                'subtitle'    => 'FAQs',
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
            [
                'page'        => 'faqs',
                'section_key' => 'intro',
                'title'       => 'Have Questions? We Have Answers',
                'subtitle'    => 'FAQs',
                'body'        => 'Find answers to the most common questions about our foundation, programs, donations, and volunteering opportunities.',
                'button_text' => null,
                'button_url'  => null,
                'is_active'   => true,
            ],
        ];

        foreach ($sections as $section) {
            PageSection::updateOrCreate(
                [
                    'page'        => $section['page'],
                    'section_key' => $section['section_key'],
                ],
                $section
            );
        }
    }
}
